Install 1.x instructions
EmmanuelRoux/ngx-matomo pull request #51
Opened 2022-06-26 14:00 UTC by namelessperson0

Fixes https://github.com/EmmanuelRoux/ngx-matomo/issues/50

2022-06-26 14:14 UTC, EmmanuelRoux commented
Hi @namelessperson0 thank you for this PR

Can you please fix the missing backquotes (see comments) and verify there is no other formatting issue?

2022-06-26 14:15 UTC, EmmanuelRoux requested changes

2022-06-26 14:15 UTC, EmmanuelRoux commented on README.md
> +`npm install --save @ngx-matomo/tracker@^1
Missing ending backquote

2022-06-26 14:15 UTC, EmmanuelRoux commented on README.md
> +`npm install --save @ngx-matomo/router@^1
Missing ending backquote

2022-07-07 15:26 UTC, EmmanuelRoux commented
@namelessperson0 do you plan to push the changes so I can merge your PR?

2022-07-09 16:06 UTC, namelessperson0 commented
> @namelessperson0 do you plan to push the changes so I can merge your PR?

The backtick issue has been fixed now.

2022-07-12 18:53 UTC, merged

2022-07-12 18:54 UTC, EmmanuelRoux commented
@namelessperson0 I've pushed a commit to fix formatting issues, now merged. Thanks for the PR! Fell free to contribute again :)