chore/bump-angular-dependencies
EmmanuelRoux/ngx-matomo pull request #61
Opened 2022-11-23 22:13 UTC by kanidjar

Today @ngx-matomo is not allowed on Angular 15 (restricted to Angular 14).

Bump Angular dependencies to ^15.0.0

2022-11-23 22:16 UTC, kanidjar commented
hi @EmmanuelRoux, i bumped all angular packages to v15 (ng update @angular-eslint/schematics @angular/cdk  @angular/cli  @angular/core @angular/material) + bumped your @angular/flex-layout to latest version (package is now deprecated).

2022-11-24 00:04 UTC, EmmanuelRoux requested changes
@kanidjar thank you very much for this PR!

2022-11-24 00:04 UTC, EmmanuelRoux commented on projects/router/package.json
> +  "version": "4.0.0",
Version will be bumped automatically when merged, so it should not be manually changed.

2022-11-24 00:04 UTC, EmmanuelRoux commented on projects/router/package.json
> +    "@ngx-matomo/tracker": "3.3.0"
Peer dependency to tracker package will be updated automatically when merged, so it should not be manually changed.

2022-11-24 00:04 UTC, EmmanuelRoux commented on projects/tracker/package.json
> +  "version": "4.0.0",
Version will be bumped automatically when merged, so it should not be manually changed.

2022-11-24 00:04 UTC, EmmanuelRoux commented on projects/tracker/schematics/version.ts
> +export const version = '^4.0.0';
Version will be bumped automatically when merged, so it should not be manually changed.

2022-11-24 00:10 UTC, EmmanuelRoux reviewed
Could you please run `npm run format` in order to reformat README toc?

2022-11-24 06:23 UTC, kanidjar commented
@EmmanuelRoux  done!

2022-11-24 11:15 UTC, EmmanuelRoux requested changes
https://github.com/EmmanuelRoux/ngx-matomo/blob/865ef4b3046bc310e5acf0db930f7c89624e3ea6/README.md?plain=1#L42
Almost ready to merge, could you please just either remove this line or replace `Angular 14` by `Angular 15`?

2022-11-24 11:31 UTC, kanidjar commented
@EmmanuelRoux all good!

2022-11-24 11:57 UTC, merged

2022-11-24 12:01 UTC, EmmanuelRoux commented
@kanidjar Thank you very much for your contribution!

2022-11-24 12:04 UTC, EmmanuelRoux commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- `v4.0.0`
- [GitHub release](https://github.com/EmmanuelRoux/ngx-matomo/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: